jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests gspread google-auth

    - name: Decode and Save Google Credentials
      run: echo ${{ secrets.GCP_CREDENTIALS }} | base64 --decode > credentials.json

    - name: Run Update Script
      env:
        AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
        AIRTABLE_TABLE_ID: ${{ secrets.AIRTABLE_TABLE_ID }}
        GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
        GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      run: python Phantombussin.py
