name: Weekly PhantomBuster Fetch and Webhook

on:
  schedule:
    # Runs every week at a specific time (2 hours after the previous one)
    - cron: '0 4 * * 1'  # This runs at 04:00 UTC every Monday
    workflow_dispatch:

jobs:
  fetch-and-send-results:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run PhantomBuster Fetch and Webhook Script
      env:
        PHANTOMBUSTER_API_KEY: ${{ secrets.PHANTOMBUSTER_API_KEY }}
      run: |
        python Phantombussin2.py
